// export-company v2 — Download everything Angus knows as structured text
import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from "jsr:@supabase/supabase-js@2"

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SUPABASE_SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': '*' } })
  }

  const authHeader = req.headers.get('Authorization')
  if (!authHeader) return new Response('Unauthorized', { status: 401 })

  const { company_id } = await req.json()
  if (!company_id) return new Response(JSON.stringify({ error: 'Missing company_id' }), { status: 400 })

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

  // Auth check
  const token = authHeader.replace('Bearer ', '')
  const { data: { user }, error: authError } = await supabase.auth.getUser(token)
  if (authError || !user) return new Response(JSON.stringify({ error: 'Invalid token' }), { status: 401 })

  // Fetch all data in parallel
  const [companyRes, knowledgeRes, correctionsRes, questionsRes] = await Promise.all([
    supabase.from('companies')
      .select('name, website, intelligence_score, domain_scores, created_at')
      .eq('id', company_id).eq('user_id', user.id).single(),
    supabase.from('knowledge_base')
      .select('data_type, value, source, confidence, created_at')
      .eq('company_id', company_id)
      .order('data_type'),
    supabase.from('knowledge_corrections')
      .select('element_label, original_value, corrected_value, applied_at')
      .eq('company_id', company_id)
      .eq('active', true)
      .order('applied_at'),
    supabase.from('onboarding_questions')
      .select('question, answer_text, domain, answered_at')
      .eq('company_id', company_id)
      .eq('status', 'answered')
      .order('priority'),
  ])

  const company = companyRes.data
  if (!company) return new Response(JSON.stringify({ error: 'Not found' }), { status: 403 })

  const domainScores = company.domain_scores || {}
  const knowledge = knowledgeRes.data || []
  const corrections = correctionsRes.data || []
  const questions = questionsRes.data || []

  const exportDate = new Date().toLocaleDateString('en-GB', {
    day: '2-digit', month: 'long', year: 'numeric'
  })

  const domainBar = (score: number) => {
    const filled = Math.round(score / 10)
    return '\u2588'.repeat(filled) + '\u2591'.repeat(10 - filled) + `  ${score}%`
  }

  const domains = ['financials', 'sales', 'marketing', 'operations', 'team', 'strategy']
  const domainLabels: Record<string, string> = {
    financials: 'Financials     ',
    sales: 'Sales & Revenue',
    marketing: 'Marketing      ',
    operations: 'Operations     ',
    team: 'Team & People  ',
    strategy: 'Strategy       ',
  }

  // Group knowledge by data_type
  const byDomain: Record<string, typeof knowledge> = {}
  for (const item of knowledge) {
    const d = item.data_type || 'general'
    if (!byDomain[d]) byDomain[d] = []
    byDomain[d].push(item)
  }

  let text = `FOUNDER ENGINE — Company Intelligence Export\n`
  text += `${'='.repeat(50)}\n`
  text += `Company: ${company.name}\n`
  text += `Website: ${company.website || 'Not provided'}\n`
  text += `Exported: ${exportDate}\n\n`

  text += `INTELLIGENCE SCORE: ${company.intelligence_score || 0}%\n\n`

  text += `DOMAIN SCORES\n`
  for (const domain of domains) {
    const score = domainScores[domain] || 0
    text += `  ${domainLabels[domain]}  ${domainBar(score)}\n`
  }
  text += `\n`

  if (knowledge.length > 0) {
    text += `WHAT ANGUS KNOWS\n${'\u2500'.repeat(40)}\n`
    for (const [domain, items] of Object.entries(byDomain)) {
      text += `\n[${domain.toUpperCase()}]\n`
      for (const item of items) {
        text += `  \u2022 ${item.value} [Source: ${item.source || 'unknown'}]\n`
      }
    }
    text += `\n`
  }

  if (corrections.length > 0) {
    text += `FOUNDER CORRECTIONS LOG\n${'\u2500'.repeat(40)}\n`
    for (const c of corrections) {
      const date = new Date(c.applied_at).toLocaleDateString('en-GB')
      text += `  [${date}] ${c.element_label}: "${c.original_value}" \u2192 "${c.corrected_value}"\n`
    }
    text += `\n`
  }

  if (questions.length > 0) {
    text += `QUESTIONS ANSWERED\n${'\u2500'.repeat(40)}\n`
    questions.forEach((q, i) => {
      text += `  ${i + 1}. ${q.question}\n     \u2192 ${q.answer_text}\n`
    })
    text += `\n`
  }

  text += `${'\u2500'.repeat(50)}\n`
  text += `Generated by Founder Engine | founderengine.ai\n`
  text += `All data belongs to you. Take it wherever you go.\n`

  const safeName = (company.name || 'export').replace(/\s+/g, '-').toLowerCase()

  return new Response(text, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': `attachment; filename="founder-engine-export-${safeName}.txt"`,
      'Access-Control-Allow-Origin': '*',
    },
  })
})
